---
language: node_js
node_js:
  - 'stable'
env:
  secure: s0j8+kX/5qJQb2DLUVSHCrFF+OkG8p//NW+lZA2GFX3JI8/beyhcJLzN+t4o9JJN2ND4n+v3e7j3BoPyE+27wdy7DF34S1OBnJ0OkIoLWUnD0LxKact068+6AV6/MxTTMrCDXWyYTb/4m7unuInLphPBGzZqrFelEpNKgh30iGMoClqr0DkpnMifoWYnhxACsrw3PfsXNyqO5iXvVxC8jdzWNrF3NrEd/5xr2+HjB7YQATpda+qqsl/CuEd5+jpSckwsr46i8urMiO0aQmNbkaxbj4FA0NG1xGtW8kJkbA4D/fK9z+nJeQJ2P6AfSG/2Pp13tQ0tIHgksl15we7jTbHw1OaxNZRjk2bKDL77yQS5TqWOAXeuYhrb9lj+hlY6d7l+S9fCSSyfJ2KIsQVCHQX9WouEjFY75IhJqNIbYv0oAjQiPIu8tidh2oBNfc8pHiLMAQ1tb1dRakoHog1KUiTpvUBq5B/5uF1x36WxEktjW/1YwB1L5uR78Y5sZymx4qKSLyetU7MONFRWWA5xJ6cDgm9QFDdtTqG1GmVPL8M3UOI7y5T7dqKDBh+npHhj74c5sZLN3NR3ZGbGJR4yQTjwgOmR2ZBMYMC5+lPeOYtl24FgRF2Beuseds4EIaKUMPSQjcW6ZrDRK9KQjsRdqo3n3JGav131wZZBztYX8jw=
cache: yarn
script:
  - yarn lint
  - yarn test
  - yarn generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
notifications:
  email: false
  slack:
    secure: VK3XBflN5dr+1W1ucmxZ89uqMcoQquePSLt2L52YGG7RPUmpjoxtGIFqlEgF379wVlNIEL7QLiTd7HI9E0h6e/e99IbJWV365putkGDHryS2+CYf8980LwVcZkR8wg4vq+VBO4kPXxEjcrqO/jeCuVJHZ+l0gFt8ekaxFLv9/ZgP5eHjjxSY/fNzegUiuydk8ebXpCr+IGCQgAjwnq0qGAmP5XH0Ro3mNqyEV7ZkgZ7IC9zcLUiqpt1tEq3mbQvTtdLcOJ3OU1iFXxlXk2h5HgvSyokmhIURtAkz24LKbWL1Peyhmo7AikwvkZrYiSnlKGREZeoZFTDqqrxweo7QsS5tWv8ixuJ2Hl6GtQT7R0OWhNmBlw2bSbag0puVKD8JvFCecl6/ROEG0WPVDQLjTvsbxpYTbCkrocVeAnCQmo63AcnuUTmc+/OAtjVtLR/P+SCouHb4Huu9Oc2OojxTiN1q1EkgPiB2q9du4yy7Re6ZnVuJkKP+/Gx7DcJFH7b9jovS3EDnqpH2f/yxwWzx5qH0nQ5w2hFb5u6HVnN4t9BiI5y5CT06JU2fk73pokdVR8GxoC0ATrEK6ROZtbyekTjK+80DpuVzaTzvPLQLweyrME3HCj+XUczTvEx+07N981I+Y+OFSQ0ji5szI/TMDUonupdByEsexdDe6XDiShA=
